// SPDX-License-Identifier: Apache-2.0
//! The compatibility matrix, generated by trying things.
//!
//! `docs/PLCOPEN_COMPATIBILITY.md` is written from this module by a test, and
//! another test fails if the committed file disagrees with what this module
//! produces now. So the matrix cannot be edited into saying something
//! flattering, and cannot drift.
//!
//! # The rule that decides every cell
//!
//! **A construct is only "round-trips" if this module round-tripped it just
//! now.** Not if the code looks as though it should; not if it worked when
//! somebody wrote it. Each row here builds a document containing that
//! construct, writes it, reads it back, and compares. A row that is not
//! exercised says `not tested`, and a row that is exercised and fails says so
//! with what came back.
//!
//! That is the whole reason for generating it. Every tool in this space claims
//! to support PLCopen XML and very few publish what is lost, because a
//! hand-written list of what works is a list of what worked once.

use crate::model::{Body, Interface, Pou, PouKind, Project, VarSection, Variable, Version};
use crate::read::read;
use crate::write::write;

/// What happened when a construct was tried.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// It came back identical.
    RoundTrips,
    /// It was written and read back as something else.
    Changed,
    /// Writing or reading it failed outright.
    Failed,
}

impl Outcome {
    /// The marker used in the table.
    ///
    /// Shapes rather than colours, for the same reason the capability table
    /// uses them: a red and green table some readers cannot distinguish is a
    /// defect.
    #[must_use]
    pub const fn marker(self) -> &'static str {
        match self {
            Self::RoundTrips => "`[x]`",
            Self::Changed => "`[~]`",
            Self::Failed => "`[ ]`",
        }
    }

    /// What it means, in words.
    #[must_use]
    pub const fn describe(self) -> &'static str {
        match self {
            Self::RoundTrips => "round-trips unchanged",
            Self::Changed => "survives, altered",
            Self::Failed => "does not survive",
        }
    }
}

/// One construct, and what happened to it.
#[derive(Debug, Clone)]
pub struct Row {
    /// What was tried.
    pub construct: &'static str,
    /// What happened.
    pub outcome: Outcome,
    /// Anything worth knowing about it.
    pub note: &'static str,
}

impl Row {
    /// A row whose round trip through salman's model tells the whole story.
    fn tried(construct: &'static str, project: &Project, note: &'static str) -> Self {
        Self {
            construct,
            outcome: try_round_trip(project),
            note,
        }
    }

    /// A row where the model round-trips and the **document** does not.
    ///
    /// This is the one place the matrix could flatter itself, and it is worth
    /// being explicit about why. A Ladder body comes back identical because
    /// salman's model of it is only the word `LD` — the contents were
    /// discarded when it was read, so writing and reading agree perfectly
    /// about a thing salman already threw away. Comparing models can never see
    /// that, so the row says so instead of showing a clean mark.
    fn lossy(construct: &'static str, project: &Project, note: &'static str) -> Self {
        let outcome = match try_round_trip(project) {
            // It survived as far as the model goes, and the document did not.
            Outcome::RoundTrips => Outcome::Changed,
            worse => worse,
        };
        Self {
            construct,
            outcome,
            note,
        }
    }
}

/// A minimal project carrying one POU.
fn with(pou: Pou) -> Project {
    Project {
        version: Version::V2_01,
        company: "salman".to_string(),
        product: "salman".to_string(),
        product_version: salman_core::VERSION.to_string(),
        name: "Compatibility".to_string(),
        pous: vec![pou],
    }
}

/// A program with one local variable of the given type.
fn program_with_variable(variable: Variable) -> Project {
    with(Pou {
        name: "Main".to_string(),
        kind: PouKind::Program,
        interface: Interface {
            return_type: None,
            sections: vec![(VarSection::Local, vec![variable])],
        },
        bodies: vec![Body::StructuredText {
            text: ";".to_string(),
            wrapper: "xhtml".to_string(),
        }],
    })
}

/// A variable of `type_name` and nothing else.
fn variable(type_name: &str) -> Variable {
    Variable {
        name: "V".to_string(),
        type_name: type_name.to_string(),
        address: None,
        initial_value: None,
    }
}

/// Writes a project, reads it back, and says what happened.
fn try_round_trip(project: &Project) -> Outcome {
    let mut bytes = Vec::new();
    if write(project, "2026-01-01T00:00:00", &mut bytes).is_err() {
        return Outcome::Failed;
    }
    match read(&bytes[..]) {
        Ok(returned) if returned == *project => Outcome::RoundTrips,
        Ok(_) => Outcome::Changed,
        Err(_) => Outcome::Failed,
    }
}

/// Every construct salman claims anything about, tried now.
#[must_use]
pub fn matrix() -> Vec<Row> {
    let mut rows = Vec::new();

    // POU kinds.
    for (kind, construct) in [
        (PouKind::Program, "`PROGRAM`"),
        (PouKind::FunctionBlock, "`FUNCTION_BLOCK`"),
        (PouKind::Function, "`FUNCTION` with a return type"),
    ] {
        let project = with(Pou {
            name: "P".to_string(),
            kind,
            interface: Interface {
                return_type: (kind == PouKind::Function).then(|| "INT".to_string()),
                sections: Vec::new(),
            },
            bodies: vec![Body::StructuredText {
                text: ";".to_string(),
                wrapper: "xhtml".to_string(),
            }],
        });
        rows.push(Row::tried(construct, &project, ""));
    }

    // Variable sections.
    for (section, construct) in [
        (VarSection::Local, "`VAR`"),
        (VarSection::Input, "`VAR_INPUT`"),
        (VarSection::Output, "`VAR_OUTPUT`"),
        (VarSection::InOut, "`VAR_IN_OUT`"),
        (VarSection::Temp, "`VAR_TEMP`"),
        (VarSection::External, "`VAR_EXTERNAL`"),
        (VarSection::Global, "`VAR_GLOBAL`"),
    ] {
        let project = with(Pou {
            name: "P".to_string(),
            kind: PouKind::Program,
            interface: Interface {
                return_type: None,
                sections: vec![(section, vec![variable("BOOL")])],
            },
            bodies: Vec::new(),
        });
        rows.push(Row::tried(construct, &project, ""));
    }

    // Types.
    rows.push(Row::tried(
        "elementary types",
        &program_with_variable(variable("BOOL")),
        "",
    ));
    rows.push(Row::lossy(
        "`LTIME`, `LDATE`, `LTOD`, `LDT`, `CHAR`, `WCHAR`",
        &program_with_variable(variable("LTIME")),
        "v2.01's type set is frozen at IEC 61131-3 2nd edition and has no element for these. \
         salman writes a named type reference, which keeps the name and changes what the \
         document means: another reader sees a user-declared type, not the elementary one",
    ));
    rows.push(Row::tried(
        "`STRING` with a declared length",
        &program_with_variable(variable("STRING[32]")),
        "the schema spells the element in lower case; an uppercase `STRING` fails validation",
    ));
    rows.push(Row::tried(
        "a user-declared type",
        &program_with_variable(variable("Axis")),
        "written as `<derived name=…/>`",
    ));

    // Variable details.
    rows.push(Row::tried(
        "an `AT %` located address",
        &program_with_variable(Variable {
            name: "V".to_string(),
            type_name: "BOOL".to_string(),
            address: Some("%QX0.0".to_string()),
            initial_value: None,
        }),
        "",
    ));
    rows.push(Row::tried(
        "an initial value",
        &program_with_variable(Variable {
            name: "V".to_string(),
            type_name: "INT".to_string(),
            address: None,
            initial_value: Some("7".to_string()),
        }),
        "",
    ));

    // Bodies.
    for (wrapper, construct) in [
        ("xhtml", "Structured Text, CODESYS-family wrapper"),
        ("p", "Structured Text, Beremiz-family wrapper"),
    ] {
        let project = with(Pou {
            name: "P".to_string(),
            kind: PouKind::Program,
            interface: Interface::default(),
            bodies: vec![Body::StructuredText {
                text: "A := 1;".to_string(),
                wrapper: wrapper.to_string(),
            }],
        });
        rows.push(Row::tried(
            construct,
            &project,
            "the wrapper a document came with is written back, so a file does not change \
             families by passing through salman",
        ));
    }

    for language in ["LD", "FBD", "SFC", "IL"] {
        let project = with(Pou {
            name: "P".to_string(),
            kind: PouKind::Program,
            interface: Interface::default(),
            bodies: vec![Body::Other {
                language: language.to_string(),
            }],
        });
        rows.push(Row::lossy(
            match language {
                "LD" => "a Ladder body",
                "FBD" => "a Function Block Diagram body",
                "SFC" => "a Sequential Function Chart body",
                _ => "an Instruction List body",
            },
            &project,
            "the element survives and its contents do not. salman does not read these \
             languages, so the contents were discarded on the way in and the model cannot \
             see the loss; `Project::unread_bodies` reports it",
        ));
    }

    // Several bodies, and several sections in a declared order.
    let many = with(Pou {
        name: "P".to_string(),
        kind: PouKind::Program,
        interface: Interface {
            return_type: None,
            sections: vec![
                (VarSection::Output, vec![variable("BOOL")]),
                (VarSection::Input, vec![variable("INT")]),
            ],
        },
        bodies: vec![
            Body::StructuredText {
                text: "A := 1;".to_string(),
                wrapper: "xhtml".to_string(),
            },
            Body::StructuredText {
                text: "B := 2;".to_string(),
                wrapper: "xhtml".to_string(),
            },
        ],
    });
    rows.push(Row::tried(
        "several bodies in one POU",
        &many,
        "the schema permits one per worksheet",
    ));
    rows.push(Row::tried(
        "variable sections in a non-standard order",
        &many,
        "the schema's unbounded choice permits any order and repeats; the order a document \
         used is preserved",
    ));

    rows
}

/// Renders the matrix as the committed Markdown.
#[must_use]
pub fn render_markdown() -> String {
    use core::fmt::Write;
    let rows = matrix();
    let mut out = String::new();

    out.push_str("# PLCopen XML compatibility\n\n");
    out.push_str(
        "*Generated by `salman_plcopen::compat`. Do not edit by hand: a test rewrites this \
         file and another test fails if it disagrees with what the code does now.*\n\n",
    );
    out.push_str(
        "`[x]` round-trips unchanged  ·  `[~]` survives, altered  ·  `[ ]` does not \
         survive\n\n",
    );
    out.push_str(
        "Every row was tried while this file was generated: a document containing that \
         construct was written, read back, and compared. Nothing here is a statement about \
         what the code looks as though it should do.\n\n",
    );
    out.push_str(
        "A `[~]` row is one where salman's **model** round-trips and the **document** does \
         not. It is marked from what salman knows it discarded rather than from the \
         comparison, because a construct thrown away on the way in comes back looking \
         perfect: the two halves agree entirely about a thing that is no longer there.\n\n",
    );

    out.push_str("| | Construct | Outcome | Notes |\n|---|---|---|---|\n");
    for row in &rows {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            row.outcome.marker(),
            row.construct,
            row.outcome.describe(),
            row.note
        );
    }

    out.push_str(
        "\n## What this does not tell you\n\n\
         **This is salman against salman.** Every row above is a document salman wrote, so \
         it establishes that salman's reader and writer agree with each other and nothing \
         more. The class of error it cannot find is the one where both share a misreading of \
         the format.\n\n\
         Closing that gap needs a corpus of real vendor exports with provenance clean enough \
         to commit, and **no such corpus exists**. The one genuine vendor export PLCopen \
         itself publishes — a CODESYS V3.5 file — has been read successfully, and it is \
         PLCopen's to distribute rather than salman's. See \
         `docs/adr/ADR-0003-plcopen-xml-canonical.md`.\n\n\
         **salman does not validate against the schema**, because it does not ship one: no \
         redistribution grant for the v2.01 schema could be found, and not finding permission \
         is not permission. A document that round-trips here has not been shown to be \
         schema-valid.\n\n\
         **No conformance is claimed**, because PLCopen runs no conformance programme for \
         this format.\n",
    );
    out
}
