[package]
name = "salman-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "salman command line interface"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["plc", "iec61131", "structured-text", "modbus", "automation"]
categories = ["command-line-utilities", "development-tools", "simulation"]

[[bin]]
name = "salman"
path = "src/main.rs"

[dependencies]
salman-core.workspace = true
salman-lang.workspace = true
salman-vm.workspace = true
salman-test.workspace = true
salman-analyse.workspace = true
salman-modbus.workspace = true
salman-project.workspace = true
clap = { version = "4", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }

[lints]
workspace = true
