// SPDX-License-Identifier: Apache-2.0
//! A golden capture, and the report salman makes of it.
//!
//! # Why salman generates its own fixture
//!
//! There is no small Modbus capture anywhere with clean, stateable provenance.
//! The Wireshark sample-capture wiki has no Modbus captures and no licence
//! statement of any kind; the best-known collection redistributes files whose
//! upstream is undocumented under a blanket repository licence that cannot
//! credibly cover third-party content; several others carry no licence at all.
//!
//! So salman makes its own. `examples/capture/conveyor.pcap` is written by
//! this test from bytes this test constructs, which means its provenance is
//! exactly the statement the project's verification rule wants: *generated by
//! salman's own harness, from these bytes, at this commit*. It is regenerated
//! rather than fetched, so it cannot drift and cannot carry someone else's
//! licence.
//!
//! # What the golden report protects
//!
//! The report is the output of every layer at once — pcap, frame decode,
//! reassembly, Modbus framing, transaction pairing, findings — so a change to
//! any of them that alters what salman says shows up as a diff a person reads
//! before committing. That is the same rule the golden-trace tests follow for
//! the runtime.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;

use salman_analyse::modbus::{Options, analyse_capture};
use salman_capture::pcap::{LinkType, Writer};
use salman_modbus::function::{ExceptionCode, FunctionCode};
use salman_modbus::pdu::{Bits, Request, Response, Words};
use salman_modbus::tcp::TcpAdu;

const CLIENT: [u8; 4] = [192, 168, 1, 10];
const SERVER: [u8; 4] = [192, 168, 1, 20];

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("the workspace root")
        .to_path_buf()
}

/// Wraps a TCP payload in TCP, IPv4 and Ethernet headers.
fn frame(outgoing: bool, seq: u32, payload: &[u8], pad_to_minimum: bool) -> Vec<u8> {
    let (from, to, sport, dport) = if outgoing {
        (CLIENT, SERVER, 51_000_u16, 502_u16)
    } else {
        (SERVER, CLIENT, 502, 51_000)
    };
    let mut tcp = Vec::new();
    tcp.extend_from_slice(&sport.to_be_bytes());
    tcp.extend_from_slice(&dport.to_be_bytes());
    tcp.extend_from_slice(&seq.to_be_bytes());
    tcp.extend_from_slice(&0_u32.to_be_bytes());
    tcp.push(0x50);
    tcp.push(0x18);
    tcp.extend_from_slice(&[0xFF, 0xFF, 0, 0, 0, 0]);
    tcp.extend_from_slice(payload);

    let total = 20 + tcp.len();
    let mut ip = vec![0x45, 0x00];
    ip.extend_from_slice(&(total as u16).to_be_bytes());
    ip.extend_from_slice(&[0, 0, 0, 0, 64, 6, 0, 0]);
    ip.extend_from_slice(&from);
    ip.extend_from_slice(&to);
    ip.extend_from_slice(&tcp);

    let mut ethernet = vec![0x00, 0x0C, 0x29, 0x11, 0x22, 0x33];
    ethernet.extend_from_slice(&[0x00, 0x0C, 0x29, 0x44, 0x55, 0x66]);
    ethernet.extend_from_slice(&0x0800_u16.to_be_bytes());
    ethernet.extend_from_slice(&ip);
    if pad_to_minimum {
        while ethernet.len() < 60 {
            ethernet.push(0x00);
        }
    }
    ethernet
}

/// Builds the golden capture.
///
/// Every frame in it is here for a reason, and the reasons are the failures
/// this whole stack exists to get right.
fn build_capture() -> Vec<u8> {
    let read_registers = Request::ReadHoldingRegisters {
        start: 0,
        quantity: 2,
    };
    let read_coils = Request::ReadCoils {
        start: 0,
        quantity: 4,
    };
    let read_past_the_end = Request::ReadHoldingRegisters {
        start: 9_000,
        quantity: 8,
    };

    let mut writer = Writer::new(LinkType::ETHERNET, 262_144);
    // A round number, so the golden report's timestamps are readable.
    let mut time = 1_700_000_000_000_000_000_u64;
    let mut seq_out = 1_u32;
    let mut seq_in = 1_u32;

    let mut push = |writer: &mut Writer, bytes: &[u8]| {
        writer.write(time, bytes.len() as u32, bytes);
        time += 2_000_000;
    };

    // 1. A bare acknowledgement, padded to the Ethernet minimum. Its six
    //    padding bytes read as an MBAP header of all zeros, so a decoder that
    //    took them as payload would report a phantom frame here.
    push(&mut writer, &frame(true, seq_out, &[], true));

    // 2-3. An ordinary exchange.
    let adu = TcpAdu::new(1, 1, read_registers.encode().unwrap()).to_vec();
    push(&mut writer, &frame(true, seq_out, &adu, false));
    seq_out += adu.len() as u32;
    let answer = TcpAdu::new(
        1,
        1,
        Response::ReadHoldingRegisters(Words::new(&[0x0142, 0x0000]).unwrap()).encode(),
    )
    .to_vec();
    push(&mut writer, &frame(false, seq_in, &answer, false));
    seq_in += answer.len() as u32;

    // 4-6. A request split across two segments mid-frame, then its answer.
    let adu = TcpAdu::new(2, 1, read_coils.encode().unwrap()).to_vec();
    let (head, tail) = adu.split_at(4);
    push(&mut writer, &frame(true, seq_out, head, false));
    push(&mut writer, &frame(true, seq_out + 4, tail, false));
    seq_out += adu.len() as u32;
    let answer = TcpAdu::new(
        2,
        1,
        Response::ReadCoils(Bits::from_iter_of([true, false, true, true]).unwrap()).encode(),
    )
    .to_vec();
    push(&mut writer, &frame(false, seq_in, &answer, false));
    seq_in += answer.len() as u32;

    // 7-8. A request the device refuses, because the address is not in its map.
    let adu = TcpAdu::new(3, 1, read_past_the_end.encode().unwrap()).to_vec();
    push(&mut writer, &frame(true, seq_out, &adu, false));
    seq_out += adu.len() as u32;
    let refusal = TcpAdu::new(
        3,
        1,
        Response::Exception {
            function: FunctionCode::READ_HOLDING_REGISTERS,
            code: ExceptionCode::ILLEGAL_DATA_ADDRESS,
        }
        .encode(),
    )
    .to_vec();
    push(&mut writer, &frame(false, seq_in, &refusal, false));
    seq_in += refusal.len() as u32;

    // 9. The same answer again, byte for byte, as a mirror port delivers it.
    push(
        &mut writer,
        &frame(false, seq_in - refusal.len() as u32, &refusal, false),
    );

    // 10. A last request nothing answers, because the capture stops here.
    let adu = TcpAdu::new(4, 1, read_registers.encode().unwrap()).to_vec();
    push(&mut writer, &frame(true, seq_out, &adu, false));

    writer.finish()
}

/// Renders an analysis as the golden report.
fn render(analysis: &salman_analyse::modbus::Analysis) -> String {
    let mut out = String::new();
    out.push_str("# salman capture report\n");
    out.push_str("#\n");
    out.push_str("# Generated by crates/salman-analyse/tests/golden.rs. Do not edit by hand.\n");
    out.push_str("# The capture beside it is generated by the same test, so its provenance is\n");
    out.push_str("# salman's own harness rather than a file of unknown origin.\n");
    out.push_str("#\n");
    out.push_str(&format!(
        "# {} frames, {} Modbus units, {} transactions paired\n\n",
        analysis.frames, analysis.adus, analysis.paired
    ));
    for finding in &analysis.findings {
        out.push_str(&finding.to_string());
        out.push_str("\n\n");
    }
    out
}

#[test]
fn the_golden_capture_and_its_report_are_what_is_committed() {
    let capture = build_capture();
    let analysis = analyse_capture("conveyor.pcap", &capture, Options::default()).unwrap();
    let report = render(&analysis);

    let capture_path = root().join("examples/capture/conveyor.pcap");
    let report_path = root().join("examples/capture/conveyor.report");

    if std::env::var_os("SALMAN_UPDATE_GOLDEN").is_some() {
        std::fs::write(&capture_path, &capture).unwrap();
        std::fs::write(&report_path, &report).unwrap();
        return;
    }

    let committed_capture = std::fs::read(&capture_path).unwrap_or_else(|_| {
        panic!(
            "{} does not exist. Run with SALMAN_UPDATE_GOLDEN=1 to write it, then read it \
             before committing",
            capture_path.display()
        )
    });
    assert_eq!(
        capture,
        committed_capture,
        "the capture this test builds is not the one committed at {}",
        capture_path.display()
    );

    let committed_report = std::fs::read_to_string(&report_path).unwrap_or_else(|_| {
        panic!(
            "{} does not exist. Run with SALMAN_UPDATE_GOLDEN=1 to write it, then read it \
             before committing",
            report_path.display()
        )
    });
    assert_eq!(
        report, committed_report,
        "what salman says about the golden capture has changed. Read the diff: if it is an \
         improvement, run with SALMAN_UPDATE_GOLDEN=1 and commit the new report"
    );
}

#[test]
fn the_golden_capture_contains_what_it_is_meant_to_contain() {
    // A golden file whose contents nobody checks is a golden file that records
    // a bug as correct. These are the specific traps the capture encodes.
    let capture = build_capture();
    let analysis = analyse_capture("conveyor.pcap", &capture, Options::default()).unwrap();

    assert_eq!(analysis.frames, 10);
    assert_eq!(
        analysis.paired, 3,
        "three requests were answered, one of them with an exception"
    );

    let ids: Vec<&str> = analysis.findings.iter().map(|f| f.id).collect();
    assert!(
        ids.contains(&"mbtcp.exception"),
        "the refusal must be reported: {ids:?}"
    );
    assert!(
        ids.contains(&"mbtcp.request.unanswered"),
        "the last request has no answer: {ids:?}"
    );
    assert!(
        ids.contains(&"mbtcp.transactions.paired"),
        "the pass proves the rest was checked: {ids:?}"
    );
    assert!(
        !ids.contains(&"mbtcp.framing.lost"),
        "the split request and the padded acknowledgement must not break framing: {ids:?}"
    );
    assert!(
        !ids.contains(&"mbtcp.response.unmatched"),
        "the duplicated answer must not look like an answer to nothing: {ids:?}"
    );
}

#[test]
fn the_capture_is_byte_identical_every_time_it_is_built() {
    // Determinism, without which a golden file is a source of noise rather
    // than of signal.
    assert_eq!(build_capture(), build_capture());
}
